source "http://rubygems.org"
# Add dependencies required to use your gem here.
# Example:
#   gem "activesupport", ">= 2.3.5"

gem 'draper'
gem 'rails'
gem 'sqlite3'
gem 'haml'
gem 'alice', :path => '../..'

